#!/usr/bin/env python3

def check_xiq_device(item, params, check_context):
    device_info = check_context["xiq_devices"][item]
    device = device_info["device"]
    uptime = device.get("system_up_time_formatted")
    hostname = device.get("hostname")
    ip_address = device.get("ip_address")
    function = device.get("device_function")
    serial = device_info["serial_number"] # Zugriff auf die Seriennummer
    mac = device_info["mac_address"] # Zugriff auf die MAC Adresse
    product = device_info["product_type"]
    software = device_info["software_version"]
    admin_state = device_info["device_admin_state"]
    policy = device_info["network_policy_name"]
    managed = device_info["managed_by"]

    output = f"Hostname: {hostname}, IP: {ip_address}, Funktion: {function}, Uptime: {uptime}, Seriennummer: {serial}, MAC: {mac}, Produkt: {product}, Software: {software}, Admin Status: {admin_state}, Policy: {policy}, Managed By: {managed}"

    return 0, output