#!/usr/bin/env python3

def check_xiq_device(item, params, check_context):
    device = check_context["xiq_devices"][item]["device"]
    uptime = device.get("system_up_time_formatted")
    hostname = device.get("hostname")
    ip_address = device.get("ip_address")
    function = device.get("device_function")

    output = f"Hostname: {hostname}, IP: {ip_address}, Funktion: {function}, Uptime: {uptime}"

    return 0, output