#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-
# +------------------------------------------------------------------+
# |             ____ _               _        __  __ _  __           |
# |            / ___| |__   ___  ___| | __   |  \/  | |/ /           |
# |           | |   | '_ \ / _ \/ __| |/ /   | |\/| | ' /            |
# |           | |___| | | |  __/ (__|   <    | |  | | . \            |
# |            \____|_| |_|\___|\___|_|\_\___|_|  |_|_|\_\           |
# |                                                                  |
# | Copyright Mathias Kettner 2018             mk@mathias-kettner.de |
# +------------------------------------------------------------------+
#
# This file is part of Check_MK.
# The official homepage is at http://mathias-kettner.de/check_mk.
#
# check_mk is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# tails. You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

#.
#   .--temperature---------------------------------------------------------.
#   |      _                                      _                        |
#   |     | |_ ___ _ __ ___  _ __   ___ _ __ __ _| |_ _   _ _ __ ___       |
#   |     | __/ _ \ '_ ` _ \| '_ \ / _ \ '__/ _` | __| | | | '__/ _ \      |
#   |     | ||  __/ | | | | | |_) |  __/ | | (_| | |_| |_| | | |  __/      |
#   |      \__\___|_| |_| |_| .__/ \___|_|  \__,_|\__|\__,_|_|  \___|      |
#   |                       |_|                                            |
#   +----------------------------------------------------------------------+
#   |                                                                      |
#   '----------------------------------------------------------------------'

check_info['enviromuxMicro'] = {
    'parse_function': parse_enviromuxMicro,
    'inventory_function': inventory_enviromuxMicro_temperature,
    'check_function': check_enviromuxMicro_temperature,
    'service_description': 'Sensor %s',
    'snmp_info': (
        '.1.3.6.1.4.1.3699.1.1.12.1.1.1.1',
        [
            "1",  # intSensorIndex
            "2",  # intSensorType
            "3",  # intSensorDescription
            #"4",  # intSensorGroupNb
            #"5",  # intSensorGroup
            "4",  # intSensorValue
            "5",  # intSensorUnit
            #"8",  # intSensorUnitName
            #"9",  # intSensorStatus
            #"10",  # intSensorMinThreshold
            #"11",  # intSensorMaxThreshold
            # These appear to only return bogus values
            #"12", # intSensorMinWarnThreshold
            #"13", # intSensorMaxWarnThreshold
        ]),
    'includes': ["temperature.include", "enviromuxMicro.include"],
    'has_perfdata': True,
    'snmp_scan_function': enviromuxMicro_scan_function,
    'group': "temperature",
}

#.
#   .--Voltage-------------------------------------------------------------.
#   |                 __     __    _ _                                     |
#   |                 \ \   / /__ | | |_ __ _  __ _  ___                   |
#   |                  \ \ / / _ \| | __/ _` |/ _` |/ _ \                  |
#   |                   \ V / (_) | | || (_| | (_| |  __/                  |
#   |                    \_/ \___/|_|\__\__,_|\__, |\___|                  |
#   |                                         |___/                        |
#   +----------------------------------------------------------------------+
#   |                                                                      |
#   '----------------------------------------------------------------------'

check_info['enviromux.voltage'] = {
    'inventory_function': inventory_enviromuxMicro_voltage,
    'check_function': check_enviromuxMicro_voltage,
    'service_description': 'Sensor %s',
    'has_perfdata': True,
    'group': "voltage",
    'default_levels_variable': "enviromux_default_levels",
    'includes': ["enviromuxMicro.include"],
}

#.
#   .--Humidity------------------------------------------------------------.
#   |              _   _                 _     _ _ _                       |
#   |             | | | |_   _ _ __ ___ (_) __| (_) |_ _   _               |
#   |             | |_| | | | | '_ ` _ \| |/ _` | | __| | | |              |
#   |             |  _  | |_| | | | | | | | (_| | | |_| |_| |              |
#   |             |_| |_|\__,_|_| |_| |_|_|\__,_|_|\__|\__, |              |
#   |                                                  |___/               |
#   +----------------------------------------------------------------------+
#   |                                                                      |
#   '----------------------------------------------------------------------'

check_info['enviromuxMicro.humidity'] = {
    'inventory_function': inventory_enviromuxMicro_humidity,
    'check_function': check_enviromuxMicro_humidity,
    'service_description': 'Sensor %s',
    'has_perfdata': True,
    'includes': ["humidity.include", "enviromuxMicro.include"],
    'group': "humidity",
}
