#!/usr/bin/env python3
# -*- encoding: utf-8; py-indent-offset: 4 -*-

def agent_my_rest_api_arguments(params, hostname, ipaddress):
    args = []
    args.append(params['uid'])
    args.append(params['pwd'])
    args.append(params['url'])
    args.append('--test')
    return args

special_agent_info['my_rest_api'] = agent_my_rest_api_arguments