#!/usr/bin/env python3
import json

def inventory_xiq_devices(check_context):
    device_data = check_context.get("xiq_devices", [])
    if device_data:
        for line in device_data:
            try:
                device = json.loads(line)
                hostname = device.get("hostname") #Hostname extrahieren
                if hostname: #Überprüfen ob Hostname vorhanden ist
                    yield (hostname, device) #Hostname als Item verwenden
                else:
                    log.warning(f"Gerät ohne Hostname gefunden (ID: {device.get('id', 'unbekannt')}). Wird nicht inventarisiert.")
            except json.JSONDecodeError:
                pass