#!/usr/bin/env python3
import json

def inventory_xiq_devices(check_context):
    device_data = check_context.get("xiq_devices", [])
    if device_data:
        for line in device_data:
            try:
                device = json.loads(line)
                function = device.get("device_function")
                if function:
                    yield (device.get("id"), {
                        "device": device,
                        "id": device.get("id"),
                        "serial_number": device.get("serial_number"),
                        "mac_address": device.get("mac_address"),
                        "product_type": device.get("product_type"),
                        "software_version": device.get("software_version"),
                        "device_admin_state": device.get("device_admin_state"),
                        "network_policy_name": device.get("network_policy_name"),
                        "managed_by": device.get("managed_by")
                    })
            except json.JSONDecodeError:
                pass