#!/usr/bin/env python3
import json

def inventory_xiq_devices(check_context):
    device_data = check_context.get("xiq_devices", [])
    if device_data:
        for line in device_data:
            try:
                device = json.loads(line)
                function = device.get("device_function")
                if function:
                    yield (device.get("id"), {"device": device}) # Gibt die Geräte ID als Item zurück
            except json.JSONDecodeError:
                pass